<html><head>
<title>Area Calculation</title>
</head>

<body>
	<h2 color="red">Area Calculation</h2>
	
	<label for="radius">Radious of Circle:</label>
	<input type="number" id="radius"><br><br>
	
	<label for="side">Side of Square:</label>
	<input type="number" id="side"><br><br>
	
	
	<label for="length">Length of Rectangle:</label>
	<input type="number" id="length"><br><br>
	
	
	<label for="breadth">Breadth of Rectangle:</label>
	<input type="number" id="breadth"><br><br>
	
	<button onclick="calculateArea()">CALCULATE</button><br><br>
	
	<p id="result_circle"></p>
	<p id="result_square"></p>
	<p id="result_rect"></p>
	
	<script>
		function calculateArea() {
		
		var radius=parseFloat(document.getElementById("radius").value); 
		var side=parseFloat(document.getElementById("side").value);
		var length=parseFloat(document.getElementById("length").value);
		var breadth=parseFloat(document.getElementById("breadth").value);
		
		var circleArea =Math.PI * radius * radius;
		var squareArea = side * side;
		var rectangleArea = length * breadth;
		
		var result1 = "AreaOfCircle" + circleArea.toFixed(2);
		var result2 = "AreaOfSquare" + squareArea.toFixed(2);
		var result3 = "AreaOfRectangle" + rectangleArea.toFixed(2);
		
		document.getElementById("result_circle").innerHTML = result1;
		document.getElementById("result_square").innerHTML = result2;
		document.getElementById("result_rect").innerHTML = result3;
	}
</script>



</body></html>
